DROP TABLE WebUser CASCADE;
DROP TABLE Forums CASCADE;
DROP TABLE Comment CASCADE;
DROP TABLE SoftwareResource CASCADE;
DROP TABLE CurriculumUtil CASCADE;
DROP TABLE HardwareResource CASCADE;
DROP TABLE ResourceRequest CASCADE;

DROP VIEW Hardware_Item_View CASCADE;

DROP TYPE GRADE_ENUM;
DROP TYPE PRIVILEGE_ENUM;
DROP TYPE REQUEST_STATUS_ENUM;
DROP TYPE USER_STATUS_ENUM;
